"""added temp_models table

Revision ID: 00791edf2f00
Revises: 5cdb6482beb6
Create Date: 2026-04-06 20:37:07.051701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00791edf2f00'
down_revision = '5cdb6482beb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_models')
    # ### end Alembic commands ###
