"""cleaned up Model table, deleted temp_models

Revision ID: 00b2d72ecfae
Revises: 933e36daebc2
Create Date: 2026-04-17 02:38:25.907135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b2d72ecfae'
down_revision = '933e36daebc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_models')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_canon_model_id'), ['canon_model_id'], unique=False)
        batch_op.drop_column('model_source')
        batch_op.drop_column('parsed_title')
        batch_op.drop_column('raw_model')
        batch_op.drop_column('parsed_aspect')
        batch_op.drop_column('parsed_mpn')
        batch_op.drop_column('raw_mpn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_mpn', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parsed_mpn', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parsed_aspect', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('raw_model', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parsed_title', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('model_source', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_models_canon_model_id'))

    op.create_table('temp_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('temp_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seen_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('temp_models_pkey')),
    sa.UniqueConstraint('temp_name', name=op.f('temp_models_temp_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
