"""removed specs from listing and put them in their own table

Revision ID: 01083a17bae8
Revises: 599e8f3d91ee
Create Date: 2026-03-09 02:44:00.415103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01083a17bae8'
down_revision = '599e8f3d91ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('cpu_freq', sa.String(length=50), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('screen_size', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('gpu', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specs_model_id'), ['model_id'], unique=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('cpu')
        batch_op.drop_column('cpu_freq')
        batch_op.drop_column('storage_type')
        batch_op.drop_column('ram')
        batch_op.drop_column('screen_size')
        batch_op.drop_column('os')
        batch_op.drop_column('gpu')
        batch_op.drop_column('display')
        batch_op.drop_column('storage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('display', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gpu', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('os', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('screen_size', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ram', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('storage_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpu_freq', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpu', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specs_model_id'))

    op.drop_table('specs')
    # ### end Alembic commands ###
