"""models.name is nullable and not unique now

Revision ID: 0e1cdd635417
Revises: 8686d444f200
Create Date: 2026-03-19 23:22:00.227216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1cdd635417'
down_revision = '8686d444f200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_models_name'))
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_listing_id'), ['listing_id'], unique=True)
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_models_listing_id'))
        batch_op.drop_index(batch_op.f('ix_models_name'))
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=True)
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
