"""added cpu_freq

Revision ID: 1514abf6181f
Revises: 1d4a91e44a16
Create Date: 2026-03-05 02:16:51.568444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1514abf6181f'
down_revision = '1d4a91e44a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('cpu_freq',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('cpu_freq',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
