"""added cpu_freq

Revision ID: 1d4a91e44a16
Revises: 7eb6e6b4a370
Create Date: 2026-03-05 02:14:53.843679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4a91e44a16'
down_revision = '7eb6e6b4a370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_freq', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('cpu_freq')

    # ### end Alembic commands ###
