"""some house cleaning

Revision ID: 243998fed13c
Revises: 54e17c20f3d9
Create Date: 2026-03-13 02:45:46.387800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243998fed13c'
down_revision = '54e17c20f3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('idx_listings_marketplace_status_model', ['marketplace', 'status', 'model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('idx_listings_marketplace_status_model')

    # ### end Alembic commands ###
