"""added processed columns to specs

Revision ID: 2dd9688dbc17
Revises: 5e44560b4fb0
Create Date: 2026-03-20 20:45:54.862357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd9688dbc17'
down_revision = '5e44560b4fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ram_processed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('storage_processed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('storage_type_processed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.drop_column('storage_type_processed')
        batch_op.drop_column('storage_processed')
        batch_op.drop_column('ram_processed')

    # ### end Alembic commands ###
