"""added marketplace to model_price_stats

Revision ID: 38fe9a1ce210
Revises: bc1515cf2401
Create Date: 2026-03-10 16:51:25.577321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fe9a1ce210'
down_revision = 'bc1515cf2401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_active_listings'), postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.drop_index(batch_op.f('idx_listings_active_model'), postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.drop_index(batch_op.f('idx_listings_marketplace_status_price'))
        batch_op.drop_index(batch_op.f('idx_listings_model_market_status_price'))

    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_column('marketplace')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_listings_model_market_status_price'), ['model_id', 'marketplace', 'status', 'price'], unique=False)
        batch_op.create_index(batch_op.f('idx_listings_marketplace_status_price'), ['marketplace', 'status', 'price'], unique=False)
        batch_op.create_index(batch_op.f('idx_listings_active_model'), ['model_id', 'price'], unique=False, postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.create_index(batch_op.f('idx_active_listings'), ['model_id', 'marketplace', 'price'], unique=False, postgresql_where="((status)::text = 'ACTIVE'::text)")

    # ### end Alembic commands ###
