"""added category id to listings

Revision ID: 390d4f773aaf
Revises: 139964ba2be6
Create Date: 2026-03-05 04:57:31.254950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390d4f773aaf'
down_revision = '139964ba2be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
