"""added temp_models table

Revision ID: 3f7e3ea04d1e
Revises: 00791edf2f00
Create Date: 2026-04-06 21:09:31.977449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7e3ea04d1e'
down_revision = '00791edf2f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_models', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['temp_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_models', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
