"""added model_id to Listing

Revision ID: 413f73dc26f5
Revises: 390d4f773aaf
Create Date: 2026-03-06 22:43:22.272624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413f73dc26f5'
down_revision = '390d4f773aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_price_history_model_id'), ['model_id'], unique=False)
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_price_history_model_id'))
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###
