"""rename sold_at to ended_at

Revision ID: 422d0817b29c
Revises: fecb1d277deb
Create Date: 2026-03-11 19:20:14.345467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '422d0817b29c'
down_revision = 'fecb1d277deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('miss_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('ended_at')

    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_model_price_stats_market_min'))
        batch_op.drop_index(batch_op.f('idx_model_price_stats_model_market'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id', 'marketplace'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('idx_model_price_stats_model_market'), ['model_id', 'marketplace'], unique=True)
        batch_op.create_index(batch_op.f('idx_model_price_stats_market_min'), ['marketplace', 'min_price'], unique=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('miss_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('sold_at')

    # ### end Alembic commands ###
