"""added cpu_freq and storage_type to Products

Revision ID: 430879bade20
Revises: 484fa7ee5e6a
Create Date: 2026-02-27 02:59:33.444930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430879bade20'
down_revision = '484fa7ee5e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_freq', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('storage_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('storage_type')
        batch_op.drop_column('cpu_freq')

    # ### end Alembic commands ###
