"""changed spec tables names

Revision ID: 484fa7ee5e6a
Revises: 6cf4436812e2
Create Date: 2026-02-27 01:00:03.550731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484fa7ee5e6a'
down_revision = '6cf4436812e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('thinkpad_models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thinkpad_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('thinkpad_models_pkey')),
    sa.UniqueConstraint('name', name=op.f('thinkpad_models_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('models')
    # ### end Alembic commands ###
