"""added indexing to some fields

Revision ID: 535d446bc298
Revises: 413f73dc26f5
Create Date: 2026-03-06 22:51:05.407404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535d446bc298'
down_revision = '413f73dc26f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('listings_ebay_item_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_listings_ebay_item_id'), ['ebay_item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_model_id'), ['model_id'], unique=False)

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_recorded_at'))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_model_id'))
        batch_op.drop_index(batch_op.f('ix_listings_ebay_item_id'))
        batch_op.create_unique_constraint(batch_op.f('listings_ebay_item_id_key'), ['ebay_item_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
