"""added indexes to models.py and rewrote alot

Revision ID: 54e17c20f3d9
Revises: c6fa477b38a9
Create Date: 2026-03-12 22:27:25.157266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e17c20f3d9'
down_revision = 'c6fa477b38a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id'], unique=False)
        batch_op.create_unique_constraint('ix_model_price_stats_model_market', ['model_id', 'marketplace'])

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_model_list'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'model_list', ['canon_model_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('price_history_listing_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('price_history_model_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'models', ['model_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('specs_listing_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specs_listing_id_fkey'), 'listings', ['listing_id'], ['id'])

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('price_history_model_id_fkey'), 'models', ['model_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('price_history_listing_id_fkey'), 'listings', ['listing_id'], ['id'])

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_model_list'), 'model_list', ['canon_model_id'], ['id'])

    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_constraint('ix_model_price_stats_model_market', type_='unique')
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id'], unique=True)

    # ### end Alembic commands ###
