"""changed pricehistory default recorded_at

Revision ID: 599e8f3d91ee
Revises: 1cd5d501460a
Create Date: 2026-03-08 22:47:48.760150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599e8f3d91ee'
down_revision = '1cd5d501460a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id'], unique=False)

    # ### end Alembic commands ###
