"""added raw values to specs

Revision ID: 5e44560b4fb0
Revises: 609dbaa107aa
Create Date: 2026-03-20 00:10:50.103693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e44560b4fb0'
down_revision = '609dbaa107aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_model_id'))
        batch_op.drop_constraint(batch_op.f('price_history_model_id_fkey'), type_='foreignkey')
        batch_op.drop_column('model_id')

    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_ram', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('raw_storage', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('raw_storage_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.drop_column('raw_storage_type')
        batch_op.drop_column('raw_storage')
        batch_op.drop_column('raw_ram')

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('price_history_model_id_fkey'), 'models', ['model_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_price_history_model_id'), ['model_id'], unique=False)

    # ### end Alembic commands ###
