"""removed model_id from listings

Revision ID: 609dbaa107aa
Revises: 0e1cdd635417
Create Date: 2026-03-19 23:42:41.153362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609dbaa107aa'
down_revision = '0e1cdd635417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_listings_marketplace_status_model'))
        batch_op.drop_index(batch_op.f('ix_listings_model_id'))
        batch_op.drop_constraint(batch_op.f('listings_model_id_fkey'), type_='foreignkey')
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('listings_model_id_fkey'), 'models', ['model_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_listings_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_listings_marketplace_status_model'), ['marketplace', 'status', 'model_id'], unique=False)

    # ### end Alembic commands ###
