"""added extra columns to models and temp_details

Revision ID: 65f93a85831b
Revises: fd0f4199275f
Create Date: 2026-03-19 22:07:03.379789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f93a85831b'
down_revision = 'fd0f4199275f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('raw_mpn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('parsed_aspect', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('parsed_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('parsed_mpn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model_source', sa.String(), nullable=True))

    with op.batch_alter_table('temp_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpn', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_details', schema=None) as batch_op:
        batch_op.drop_column('mpn')

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('model_source')
        batch_op.drop_column('parsed_mpn')
        batch_op.drop_column('parsed_title')
        batch_op.drop_column('parsed_aspect')
        batch_op.drop_column('raw_mpn')
        batch_op.drop_column('raw_model')

    # ### end Alembic commands ###
