"""changed spec tables names

Revision ID: 6cf4436812e2
Revises: 8a480930e102
Create Date: 2026-02-27 00:58:57.260316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf4436812e2'
down_revision = '8a480930e102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size')
    )
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size')
    )
    op.drop_table('cpus')
    op.drop_table('rams')
    op.drop_table('storages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('size', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('storages_pkey')),
    sa.UniqueConstraint('size', name=op.f('storages_size_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('rams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('size', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rams_pkey')),
    sa.UniqueConstraint('size', name=op.f('rams_size_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cpus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cpus_pkey')),
    sa.UniqueConstraint('name', name=op.f('cpus_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('storage')
    op.drop_table('ram')
    op.drop_table('cpu')
    # ### end Alembic commands ###
