"""added sold status

Revision ID: 6d01050b7a68
Revises: dd0b51d294fe
Create Date: 2026-02-21 20:05:31.370942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d01050b7a68'
down_revision = 'dd0b51d294fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('sold_at')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('first_seen')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
