"""removed specs from listing and put them in their own table

Revision ID: 7471f8cf62f0
Revises: 01083a17bae8
Create Date: 2026-03-09 03:22:42.879692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7471f8cf62f0'
down_revision = '01083a17bae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_specs_model_id'))
        batch_op.create_index('idx_specs_search', ['cpu', 'ram', 'storage'], unique=False)
        batch_op.create_index(batch_op.f('ix_specs_listing_id'), ['listing_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('specs_model_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'])
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specs_model_id_fkey'), 'models', ['model_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_specs_listing_id'))
        batch_op.drop_index('idx_specs_search')
        batch_op.create_index(batch_op.f('ix_specs_model_id'), ['model_id'], unique=False)
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
