"""just a fe tweaks

Revision ID: 7506d8516672
Revises: 8f58b1c402c1
Create Date: 2026-03-24 16:54:25.553392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7506d8516672'
down_revision = '8f58b1c402c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id'], unique=False)
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
