"""added more columns to listings from old models

Revision ID: 7eb6e6b4a370
Revises: d640d8a3af93
Create Date: 2026-03-05 01:37:38.933984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb6e6b4a370'
down_revision = 'd640d8a3af93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('sold_at')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('first_seen')
        batch_op.drop_column('status')
        batch_op.drop_column('listing_type')

    # ### end Alembic commands ###
