"""initial schema

Revision ID: 8021d616c2fe
Revises: 
Create Date: 2026-02-26 23:59:15.998166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8021d616c2fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('marketplace_id', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=50), nullable=True),
    sa.Column('storage', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ebay_item_id', sa.String(length=50), nullable=False),
    sa.Column('marketplace', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebay_item_id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('listings')
    op.drop_table('products')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
