"""made listing.product_id nullable

Revision ID: 810bd221eb6f
Revises: c2fa00de2988
Create Date: 2026-03-04 04:14:54.292480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810bd221eb6f'
down_revision = 'c2fa00de2988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
