"""set index=True on status,marketplace,slug

Revision ID: 832733e57745
Revises: 0da73f45d8f7
Create Date: 2026-02-27 23:19:50.018349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832733e57745'
down_revision = '0da73f45d8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_marketplace'), ['marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_marketplace'))

    # ### end Alembic commands ###
