"""added currency to listings

Revision ID: 849ef045e916
Revises: 0dcde6ac0da1
Create Date: 2026-03-05 00:54:52.433337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849ef045e916'
down_revision = '0dcde6ac0da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
