"""added cpu_num to specs

Revision ID: 85eab2bd6cd1
Revises: bbac966dd1e1
Create Date: 2026-04-20 00:25:40.304354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85eab2bd6cd1'
down_revision = 'bbac966dd1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_num', sa.Text(), nullable=True))

    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.drop_column('cpu_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_num', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('model_list', schema=None) as batch_op:
        batch_op.drop_column('cpu_num')

    # ### end Alembic commands ###
