"""first

Revision ID: 8c5c35cf08cb
Revises: 
Create Date: 2026-03-07 22:58:54.815397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5c35cf08cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('temp_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('cpu_freq', sa.String(length=50), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('screen_size', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('gpu', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('seller_username', sa.String(), nullable=True),
    sa.Column('seller_feedback_score', sa.Integer(), nullable=True),
    sa.Column('seller_feedback_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=True),
    sa.Column('ebay_item_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('item_url', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebay_item_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=True),
    sa.Column('ebay_item_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('item_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('cpu_freq', sa.String(length=50), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('storage', sa.String(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('screen_size', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('gpu', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_ebay_item_id'), ['ebay_item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_price_history_model_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_model_id'))
        batch_op.drop_index(batch_op.f('ix_listings_ebay_item_id'))

    op.drop_table('listings')
    op.drop_table('temp_summaries')
    op.drop_table('temp_details')
    op.drop_table('models')
    # ### end Alembic commands ###
