"""removed parse table

Revision ID: 8f58b1c402c1
Revises: 438b7b792781
Create Date: 2026-03-22 18:26:45.457997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f58b1c402c1'
down_revision = '438b7b792781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('model_candidate_raw_model', sa.String(), nullable=True),
    sa.Column('model_candidate_title', sa.String(), nullable=True),
    sa.Column('model_candidate_mpn', sa.String(), nullable=True),
    sa.Column('model_match_raw_model', sa.String(), nullable=True),
    sa.Column('model_match_title', sa.String(), nullable=True),
    sa.Column('model_match_mpn', sa.String(), nullable=True),
    sa.Column('model_confidence_raw_model', sa.Float(), nullable=True),
    sa.Column('model_confidence_title', sa.Float(), nullable=True),
    sa.Column('model_confidence_mpn', sa.Float(), nullable=True),
    sa.Column('model_name_resolved', sa.String(), nullable=True),
    sa.Column('model_confidence_resolved', sa.Float(), nullable=True),
    sa.Column('model_source_resolved', sa.String(), nullable=True),
    sa.Column('model_method_resolved', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parse_listing_id'), ['listing_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parse_listing_id'))

    op.drop_table('parse')
    # ### end Alembic commands ###
