"""added seen_count to  temp_models table

Revision ID: 933e36daebc2
Revises: 3f7e3ea04d1e
Create Date: 2026-04-08 20:40:10.496986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933e36daebc2'
down_revision = '3f7e3ea04d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_models', schema=None) as batch_op:
        batch_op.drop_column('seen_count')

    # ### end Alembic commands ###
