"""added more columns to Listing inline with localizedaspects

Revision ID: 958d3d43b098
Revises: 9ab5e079c645
Create Date: 2026-03-05 00:31:50.357151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958d3d43b098'
down_revision = '9ab5e079c645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screen_size', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('display', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gpu', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('os')
        batch_op.drop_column('gpu')
        batch_op.drop_column('display')
        batch_op.drop_column('screen_size')

    # ### end Alembic commands ###
