"""added cpu_num to specs

Revision ID: 98e17ae71623
Revises: 85eab2bd6cd1
Create Date: 2026-04-20 00:31:23.694644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e17ae71623'
down_revision = '85eab2bd6cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_num', sa.Text(), nullable=True))

    with op.batch_alter_table('model_list', schema=None) as batch_op:
        batch_op.drop_column('cpu_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_num', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('cpu', schema=None) as batch_op:
        batch_op.drop_column('cpu_num')

    # ### end Alembic commands ###
