"""added item_url to Listing

Revision ID: 9ab5e079c645
Revises: a647d2a9e325
Create Date: 2026-03-04 23:39:26.249970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab5e079c645'
down_revision = 'a647d2a9e325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_url', sa.Text(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('item_url')

    # ### end Alembic commands ###
