"""added url to Listing

Revision ID: a647d2a9e325
Revises: 1a7b4d7e2e11
Create Date: 2026-03-04 23:35:01.014994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a647d2a9e325'
down_revision = '1a7b4d7e2e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
