"""added index to models

Revision ID: aaa154613698
Revises: 7471f8cf62f0
Create Date: 2026-03-09 04:05:20.949170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa154613698'
down_revision = '7471f8cf62f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('models_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_name'))
        batch_op.create_unique_constraint(batch_op.f('models_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
