"""added cpu_num to specs

Revision ID: bbac966dd1e1
Revises: 00b2d72ecfae
Create Date: 2026-04-20 00:05:48.082077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbac966dd1e1'
down_revision = '00b2d72ecfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_num', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specs', schema=None) as batch_op:
        batch_op.drop_column('cpu_num')

    # ### end Alembic commands ###
