"""moved slug to model_list and added canon_model_id to models

Revision ID: c6fa477b38a9
Revises: 422d0817b29c
Create Date: 2026-03-12 21:45:49.365906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fa477b38a9'
down_revision = '422d0817b29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_list', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_market'))
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id', 'marketplace'], unique=True)
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_market'), ['model_id', 'marketplace'], unique=True)

    with op.batch_alter_table('model_list', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
