"""added currency to listings should work this time

Revision ID: d640d8a3af93
Revises: 849ef045e916
Create Date: 2026-03-05 01:04:55.765918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd640d8a3af93'
down_revision = '849ef045e916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
