"""added ebay_item_id to tempdetails

Revision ID: f21df5e6818e
Revises: 8c5c35cf08cb
Create Date: 2026-03-07 23:11:59.032887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21df5e6818e'
down_revision = '8c5c35cf08cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ebay_item_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['ebay_item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ebay_item_id')

    # ### end Alembic commands ###
