"""cleaning

Revision ID: fd0f4199275f
Revises: 243998fed13c
Create Date: 2026-03-13 02:48:33.400489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0f4199275f'
down_revision = '243998fed13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('idx_listings_marketplace_status_price', ['marketplace', 'status', 'price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('idx_listings_marketplace_status_price')

    # ### end Alembic commands ###
