"""added item_country to models and 

Revision ID: fecb1d277deb
Revises: 38fe9a1ce210
Create Date: 2026-03-10 23:11:16.176182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecb1d277deb'
down_revision = '38fe9a1ce210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('item_country',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_listings_market_model_price'), postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.drop_index(batch_op.f('idx_listings_model_price'), postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.drop_index(batch_op.f('idx_listings_stats'), postgresql_where="((status)::text = 'ACTIVE'::text)")

    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('model_price_stats_unique'), type_='unique')
        batch_op.create_index(batch_op.f('ix_model_price_stats_model_id'), ['model_id', 'marketplace'], unique=True)

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_price_history_listing_time'))

    with op.batch_alter_table('temp_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_country', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_summaries', schema=None) as batch_op:
        batch_op.drop_column('item_country')

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_price_history_listing_time'), ['listing_id', 'recorded_at'], unique=False)

    with op.batch_alter_table('model_price_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_price_stats_model_id'))
        batch_op.create_unique_constraint(batch_op.f('model_price_stats_unique'), ['model_id', 'marketplace'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_listings_stats'), ['model_id', 'marketplace'], unique=False, postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.create_index(batch_op.f('idx_listings_model_price'), ['model_id', 'price'], unique=False, postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.create_index(batch_op.f('idx_listings_market_model_price'), ['marketplace', 'model_id', 'price'], unique=False, postgresql_where="((status)::text = 'ACTIVE'::text)")
        batch_op.alter_column('item_country',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###
